language: ruby
sudo: false

notifications:
  email: false

rvm:
  - 2.4.3

before_install:
  - gem install bundler

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  
jdk: oraclejdk8

script: rake

env:
 - "RAILS_VERSION=5.1.6"
